config/routes.rb
Rails.application.routes.draw do
  root 'employees#manage_employees'

  get '/add_view_edit_employee/(:type)/(:token)',to: 'employees#add_view_edit_employee', as: 'add_view_edit_employee'
  post '/create_and_update_employee/(:type)/(:token)',to:'employees#create_and_update_employee', as: 'create_and_update_employee'
  get '/manage_employees', to: 'employees#manage_employees', as: 'manage_employees'
  get '/get_employee_data', to: 'employees#get_employee_data', as: 'get_employee_data'
  get '/delete_reason_lightbox/:user_token', to: 'employees#delete_reason_lightbox', as: 'delete_reason_lightbox'

  get '/add_view_edit_bill/(:type)/(:user_token)/(:token)',to: 'bills#add_view_edit_bill', as: 'add_view_edit_bill'
  post '/create_and_update_bill/(:type)/(:user_token)/(:token)',to:'bills#create_and_update_bill', as: 'create_and_update_bill'
  get '/manage_bills/:user_token', to: 'bills#manage_bills', as: 'manage_bills'
  get '/get_bill_data/(:user_token)', to: 'bills#get_bill_data', as: 'get_bill_data'
  get '/delete_reason_lightbox/:user_token/:token', to: 'bills#delete_reason_lightbox', as: 'bill_delete_reason_lightbox'
end

app/models/employee.rb
class Employee < ApplicationRecord
  before_create :generate_token
  validates :token, uniqueness: true

  has_many :bills, dependent: :destroy

  validates :first_name, :last_name, :email, :designation, presence: true
  validates :email, uniqueness: true

  private

  def generate_token
    begin
      self.token = SecureRandom.hex(10)
    end while self.class.exists?(token: token)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def add_view_edit_employee
    @readonly = false
    if params[:type].to_i == 1
      @employee_detail = Employee.new
      @disabled = " "
    elsif params[:type].to_i == 2
      @employee_detail = Employee.find_by_token(params[:token])
      @disabled = " "
      
    elsif params[:type].to_i == 3
      @employee_detail = Employee.find_by_token(params[:token])
      @readonly = true
      @disabled = 'disabled'
    end
  end

  def create_and_update_employee
    if params[:type].to_i == 1
      @employee_detail = Employee.create!(employee_params)
      redirect_to manage_employees_path(type: 2, token: @employee_detail.token), notice: (t :create_update_employee, type: 'created')
    elsif params[:type].to_i == 2
      @employee_detail = Employee.find_by_token(params[:token])
      @employee_detail.update!(employee_params)
      redirect_to manage_employees_path, notice: (t :create_update_employee, type: 'updated')
    elsif params[:type].to_i == 4
        @employee_detail = Employee.find_by_token(params[:token])
        @employee_detail.destroy
        redirect_to manage_employees_path, notice: ("Deleted_Successfully")
      end
  end

  def manage_employees
  end

  def get_employee_data
    @search_query = nil
    if params[:search]
      if params[:search][:value]
        @search_query = "first_name LIKE \'%"+params[:search][:value]+"%\'"
      end
    end
    _sorting = 'DESC'
    if params[:data_sorting] != ''
      _sorting = 'ASC'
    end
    @employee_array = []
    @employee_detail = Employee.where.not(token: nil).where(@search_query).order(first_name: _sorting)
    @employee_detail.each do |employee|
      @employee_name = employee.first_name+" "+employee.last_name
      @employee_email = employee.email
      @employee_designation = employee.designation
      @bill_icon = "<a href= '#{manage_bills_path(user_token: employee.token)}' class='dt-action-link-active mr-1' data-toggle='tooltip' data-original-title= 'View'> <i class='fa fa-file dt-more-action-icon-active'></i></a>"
      view_icon = "<a href= '#{add_view_edit_employee_path(type: 3, token: employee.token)}' class='dt-action-link-active mr-1' data-toggle='tooltip' data-original-title= 'View'> <i class='fa fa-eye dt-more-action-icon-active'></i></a>"
      edit_icon = "<a href= #{add_view_edit_employee_path(type: 2, token: employee.token)} class='dt-action-link-active mr-1' data-toggle='tooltip' data-original-title='Edit'> <i class='fa fa-edit dt-more-action-icon-active'></i></a>"
      delete_icon = "<a data-toggle='tooltip' data-original-title='Delete' class='dt-action-link-active' onclick=\"delete_reason('#{employee.token}')\"><i class='fa fa-trash dt-more-action-icon-active'></i></a>"
      actions = "<span class='dt-more-action-span dt-more-action-supplier-span' id='target_div_#{employee.id}'>"+edit_icon+view_icon+delete_icon+"</span><div><a class='dt-action-link-active' href='javascript:void(0);' onclick=\"load_more_action_menu(#{employee.id})\"><i class='fa fa-bars dt-more-action-icon-active'></i></a></div>"
      @employee_array << { employee_name: @employee_name, email: @employee_email, designation: @employee_designation, manage_bill: @bill_icon, action: actions}
    end 
    supplier_hash = {data: @employee_array}
    respond_to do |format|
      format.html { render json: JSON.pretty_generate(supplier_hash), status: 200 }
    end
  end

  def delete_reason_lightbox
    respond_to do |format|
      format.html { render partial: 'delete_reason_lightbox' }
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :designation)
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_delete_reason_lightbox.html.erb
<%= form_with url: create_and_update_employee_path(type:4, token: params[:user_token]), method: :post, id: 'delete_form' do |form| %>
  <div class='modal-body'>
    <%= form.text_area :reason, rows: "6", cols: "15", id: 'reason',  class: 'form-control'%>
  </div>
  <div class='modal-footer'>
    <%= form.submit 'Submit', type: :button, class:'btn btn-primary waves-effect waves-light', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: 'OK', onclick: 'submit_valid()'%>
    <%= form.button 'Cancel', type: :button, class:'btn btn-primary waves-effect waves-light', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: 'Cancel', onclick: 'HideThirdDialog()'%>
  </div>
<%end%>

app/views/employees/_form.html.erb
<%= form_for(:employee, url: create_and_update_employee_path(token: params[:token], type: params[:type]), :html => { :id => 'add_employee_form' }) do |f| %>
  <div class= "row">
    <div class = "col-3">
      <%= f.label :first_name, 'First Name', class: "control-label required"%>
      <%= f.text_field :first_name, id: 'first_name',  class: 'form-control', placeholder: 'First Name', value: @employee_detail&.first_name, readonly: @readonly%>
    </div>

    <div class = "col-3">
      <%= f.label :last_name, 'Last Name', class: "control-label required"%>
      <%= f.text_field :last_name, id: 'last_name',  class: 'form-control', placeholder: 'Last Name', value: @employee_detail&.last_name, readonly: @readonly%>
    </div>

    <div class = "col-3">
      <%= f.label :email,'Email', class: "control-label required"%>
      <%= f.email_field :email, id: 'email', class: 'form-control', value: @employee_detail&.email, placeholder: 'Email', readonly: @readonly%>
    </div>

    <div class = "col-3">
      <%= f.label :Designation, 'Designation', class: "control-label"%>
      <%= f.text_field :designation ,id: 'designation', class: 'form-control', placeholder: 'Designation', value: @employee_detail&.designation, readonly: @readonly%>
    </div>
  </div>


  <div class="field_wrapper" style = "margin-top: 15px;"></div>
  <% if params[:type].to_i == 1 %>
    <div class = "text-right">
      <%= f.button 'Refresh', type: :reset, class: 'btn btn-primary mr-2', title: 'Refresh'%>
      <%= f.submit 'Save', onclick: 'submit_form()', type: :button, class:'btn btn-primary'%>
    </div>
  <% elsif params[:type].to_i == 2 %>
    <div class = "text-right">
      <%= f.button 'Refresh', type: :reset, class: 'btn btn-primary mr-2', title: 'Refresh'%>
      <%= f.submit 'Update', onclick: 'submit_form()', type: :button, class:'btn btn-primary'%>
    </div>
  <% elsif params[:type].to_i == 3 %>
    <div class = "text-right">
      <%= link_to 'Back', :back, class: 'btn btn-primary', role: 'button' %>
    </div>
  <%end%>
<%end%>

<script type="text/javascript">
  function submit_form(){
    if($('#first_name').val() == 0){
      alert_message('Please Enter First Name', 'info', 'OK');
      return false;
    }
    if($('#last_name').val() == 0){
      alert_message('Please Enter Last Name', 'info', 'OK');
      return false;
    }
    if($('#email').val() == 0){
      alert_message('Please Enter Email', 'info', 'OK');
      return false;
    }
     $('#add_employee_form').submit();
  }

</script>

app/views/employees/add_view_edit_employee.html.erb
<div class="card">
  <div class="card-body table-view">
    <% if params[:type].to_i == 1 %>
      <div><label style="font-size: 40px;">Add Employee</lable></div>
      <br><br>
    <% elsif params[:type].to_i == 2 %>
      <div><label style="font-size: 40px;">Edit Employee</lable></div>
      <br><br>
    <% elsif params[:type].to_i == 3 %>
      <div><label style="font-size: 40px;">View Employee</lable></div>
      <br><br>
    <%end%>
    <%= render 'form' %>
  </div>
</div>

app/views/employees/manage_employees.html.erb
<div class="card">
  <div class="card-body table-view">
    <div id="add_new_button" class = "text-right"><%= link_to 'Add Employee', add_view_edit_employee_path(type: 1), class: 'btn btn-primary', role: 'button' %></div>
    <div class="table-responsive pt-4">
      <table id="manage_employees_table" class="table"></table>
    </div>
</div>
<script>
  var savedSearchIndex = '';
  supplier_table = $('#manage_employees_table').DataTable({
        dom: 'frti',
        stateSave: true,
        stateDuration: -1,
        responsive: false,
        autoWidth: false,
        rowGroup: false, 
        stateSaveParams: function(settings, data) {
        },
        stateLoadParams: function(settings, data) {
          data.search.search = savedSearchIndex;
        },
        initComplete: function(settings, json) {
          this.api().search(savedSearchIndex).draw();
          $('.dataTables_filter').attr('data-original-title', 'Please type the search term and press "Enter" or click the search icon').tooltip();
        },
        pageLength: 100,
        paging: true,
        searchDealy: 3000,
        processing: true,
        serverSide: true,
        ajax: {
          url: '<%=get_employee_data_path%>',
          data: function (d) {
            sorting_column = null
             $.each(d.order, function(){
                if (this.dir == 'asc') {
                  sorting_column = this
                }
              })
            return $.extend( {}, d, {
              data_sorting: sorting_column,
            });
          },
          error: function() {
            alert_message('<%= t :grid_load_data_error, grid_type: 'Supplier' %>', 'info', 'OK')
          },
          complete: function(data, settings) {
            
          }
        },
        columns: [
          { title: 'Employee Name', data: 'employee_name', width: "35%", className: 'data-table-content-center'},
          { title: 'Email', data: 'email', width: "35%", orderable: false, className: 'data-table-content-center'},
          { title: 'Designation', data: 'designation', width: "15%", orderable: false, className: 'data-table-content-center' },
          { title: 'Manage Bill', data: 'manage_bill', width: "5%", orderable: false, className: 'data-table-content-center' },
          { title: 'Actions', data: 'action', width: "10%", orderable: false, className: 'data-table-content-center' }
        ],
        deferRender: true,
        orderClasses: false,
        scrollCollapse: true,
        scrollY: 320,
        scrollX: true,
        scrollCollapse: true,
        columnDefs: [
          {targets: [0], searchable: true}
        ],
        language: {
          search: "_INPUT_",
          searchPlaceholder: "Search Company Name",
          emptyTable: "No Record(s) Found",
          infoEmpty: "",
          zeroRecords: "No Record(s) Found",
          loadingRecords: "Loading...",
          loadingRecords: '<i class="fas fa-spinner fa-pulse fa-2x fa-fw"></i>',
          info: "Showing <b>_START_ to _END_</b> (of _TOTAL_)",
          infoFiltered: "",
          processing: '<i class="fas fa-spinner fa-pulse fa-2x fa-fw"></i>'
        },
        order: [[0,"asc"]],
        stripeClasses: ['odd-row', 'even-row'],
      });

  function delete_reason(user_token) {
    $.when(load_third_page("/delete_reason_lightbox/"+user_token, "", "Delete", "GET", "550", "HideThirdDialog()")).then(function() {
      $("body").addClass("modal-open");
      load_maxlength('supplier_delist_relist_other_reason', 'bottom');
      $('[data-toggle="tooltip"]').tooltip();
    });
  }

  function submit_valid() {
    if($('#delete_reason').val() == '') {
      alert_message('Please Provide reason for delete', 'info', 'OK');
      return false;
    } else {
      $('#delete_form').submit();
    }
  }
</script>