config/routes.rb
Rails.application.routes.draw do
  root 'employees#manage_employees'

  get '/add_view_edit_employee/(:type)/(:token)',to: 'employees#add_view_edit_employee', as: 'add_view_edit_employee'
  post '/create_and_update_employee/(:type)/(:token)',to:'employees#create_and_update_employee', as: 'create_and_update_employee'
  get '/manage_employees', to: 'employees#manage_employees', as: 'manage_employees'
  get '/get_employee_data', to: 'employees#get_employee_data', as: 'get_employee_data'
  get '/delete_reason_lightbox/:user_token', to: 'employees#delete_reason_lightbox', as: 'delete_reason_lightbox'

  get '/add_view_edit_bill/(:type)/(:user_token)/(:token)',to: 'bills#add_view_edit_bill', as: 'add_view_edit_bill'
  post '/create_and_update_bill/(:type)/(:user_token)/(:token)',to:'bills#create_and_update_bill', as: 'create_and_update_bill'
  get '/manage_bills/:user_token', to: 'bills#manage_bills', as: 'manage_bills'
  get '/get_bill_data/(:user_token)', to: 'bills#get_bill_data', as: 'get_bill_data'
  get '/delete_reason_lightbox/:user_token/:token', to: 'bills#delete_reason_lightbox', as: 'bill_delete_reason_lightbox'
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :employee
  before_create :generate_token
  validates :token, uniqueness: true
  validates :employee, presence: true

  validates :amount, :bill_type, :employee_id, presence: true

  private

  def generate_token
    begin
      self.token = SecureRandom.hex(10)
    end while self.class.exists?(token: token)
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def add_view_edit_bill
    @employee_id = Employee.find_by_token(params[:user_token])
    @readonly = false
    if params[:type].to_i == 1
      @bill_detail = Bill.new
      @disabled = " "
    elsif params[:type].to_i == 2
      @bill_detail = Bill.find_by_token(params[:token])
      @disabled = " "
    elsif params[:type].to_i == 3
      @bill_detail = Bill.find_by_token(params[:token])
      @readonly = true
      @disabled = 'disabled'
    end
  end

  def create_and_update_bill
    @employee = Employee.find_by_token(params[:user_token])

    if params[:type].to_i == 1
      @bill_detail = Bill.new(bill_params)
      @bill_detail.employee = @employee
      @bill_detail.save!
      redirect_to manage_bills_path(type: 2, token: @bill_detail.token), notice: (t :create_update_bill, type: 'created')
    elsif params[:type].to_i == 2
      @bill_detail = Bill.find_by_token(params[:token])
      @bill_detail.update!(bill_params)
      redirect_to manage_bills_path, notice: (t :create_update_bill, type: 'updated')
    elsif params[:type].to_i == 4
      @bill_detail = Bill.find_by_token(params[:token])
      @bill_detail.destroy
      redirect_to manage_bills_path, notice: ("Deleted_Successfully")
    end
  end


  def manage_bills
    @employee = Employee.find_by_token(params[:user_token])
  end

  def get_bill_data
    @search_query = nil
    if params[:search]
      if params[:search][:value]
        @search_query = "bill_type LIKE \'%"+params[:search][:value]+"%\'"
      end
    end
    _sorting = 'DESC'
    if params[:data_sorting] != ''
      _sorting = 'ASC'
    end
    @bill_array = []
    @bill_detail = Bill.where.not(token: nil).where(@search_query).order(bill_type: _sorting)
    @employee = Employee.find_by_token(params[:user_token])
    @bill_detail.each do |bill|
      @bill_type = bill.bill_type
      @bill_amount = bill.amount
      @employee_id = bill.employee_id
      @employee_name = @employee.first_name+" "+@employee.last_name
      view_icon = "<a href= '#{add_view_edit_bill_path(type: 3, user_token: @employee.token,token: bill.token)}' class='dt-action-link-active mr-1' data-toggle='tooltip' data-original-title= 'View'> <i class='fa fa-eye dt-more-action-icon-active'></i></a>"
      edit_icon = "<a href= #{add_view_edit_bill_path(type: 2, user_token: @employee.token, token: bill.token)} class='dt-action-link-active mr-1' data-toggle='tooltip' data-original-title='Edit'> <i class='fa fa-edit dt-more-action-icon-active'></i></a>"
      delete_icon = "<a data-toggle='tooltip' data-original-title='Delete' class='dt-action-link-active' onclick=\"delete_reason('#{bill.token}','#{@employee.token}')\"><i class='fa fa-trash dt-more-action-icon-active'></i></a>"
      actions = "<span class='dt-more-action-span dt-more-action-supplier-span' id='target_div_#{bill.id}'>"+edit_icon+view_icon+delete_icon+"</span><div><a class='dt-action-link-active' href='javascript:void(0);' onclick=\"load_more_action_menu(#{bill.id})\"><i class='fa fa-bars dt-more-action-icon-active'></i></a></div>"
      @bill_array << { bill_type: @bill_type, bill_amount: @bill_amount, employee_id: @employee_id, employee_name: @employee_name, action: actions}
    end 
    supplier_hash = {data: @bill_array}
    respond_to do |format|
      format.html { render json: JSON.pretty_generate(supplier_hash), status: 200 }
    end
  end

  def delete_reason_lightbox
    respond_to do |format|
      format.html { render partial: 'delete_reason_lightbox' }
    end
  end

  private

  def bill_params
    params.require(:bill).permit(:bill_type, :amount, :employee_id)
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_delete_reason_lightbox.html.erb
<%= form_with url: create_and_update_bill_path(type:4, user_token: params[:user_token], token: params[:token]), method: :post, id: 'delete_form' do |form| %>
  <div class='modal-body'>
    <%= form.text_area :reason, rows: "6", cols: "15", id: 'reason',  class: 'form-control'%>
  </div>
  <div class='modal-footer'>
    <%= form.submit 'Submit', type: :button, class:'btn btn-primary waves-effect waves-light', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: 'OK', onclick: 'submit_valid()'%>
    <%= form.button 'Cancel', type: :button, class:'btn btn-primary waves-effect waves-light', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: 'Cancel', onclick: 'HideThirdDialog()'%>
  </div>
<%end%>

app/views/bills/_form.html.erb
<%= form_for(:bill, url: create_and_update_bill_path(type: params[:type],user_token: params[:user_token],token: params[:token]), :html => { :id => 'add_bill_form' }) do |f| %>
  <div class= "row">
    <div class = "col-3">
      <%= f.label :bill_type, 'Bill Type', class: "control-label required"%>
      <%= f.text_field :bill_type, id: 'bill_type',  class: 'form-control', placeholder: 'Bill Type', value: @bill_detail&.bill_type, readonly: @readonly%>
    </div>

    <div class = "col-3">
      <%= f.label :amount, 'Amount', class: "control-label required"%>
      <%= f.number_field :amount, id: 'amount',  class: 'form-control', placeholder: 'Bill Amount', value: @bill_detail&.amount, readonly: @readonly%>
    </div>

    <div class = "col-3">
      <% if params[:type].to_i == 1 and params[:type].to_i == 2%>
        <%= f.hidden_field :employee_id, value:@employee_id.token%>
      <% elsif params[:type].to_i == 3%>
        <%= f.label :employee_id,'Employee Id', class: "control-label required"%>
        <%= f.number_field :employee_id, id: 'employee_id', class: 'form-control', value: @bill_detail&.employee_id, placeholder: 'Employee Id', readonly: @readonly%>
      <% end%>
    </div>

  </div>


  <div class="field_wrapper" style = "margin-top: 15px;"></div>
  <% if params[:type].to_i == 1 %>
    <div class = "text-right">
      <%= f.button 'Refresh', type: :reset, class: 'btn btn-primary mr-2', title: 'Refresh'%>
      <%= f.submit 'Save', onclick: 'submit_form()', type: :button, class:'btn btn-primary'%>
    </div>
  <% elsif params[:type].to_i == 2 %>
    <div class = "text-right">
      <%= f.button 'Refresh', type: :reset, class: 'btn btn-primary mr-2', title: 'Refresh'%>
      <%= f.submit 'Update', onclick: 'submit_form()', type: :button, class:'btn btn-primary'%>
    </div>
  <% elsif params[:type].to_i == 3 %>
    <div class = "text-right">
      <%= link_to 'Back', :back, class: 'btn btn-primary', role: 'button' %>
    </div>
  <%end%>
<%end%>

<script type="text/javascript">
  function submit_form(){
    if($('#first_name').val() == 0){
      alert_message('Please Enter First Name', 'info', 'OK');
      return false;
    }
    if($('#last_name').val() == 0){
      alert_message('Please Enter Last Name', 'info', 'OK');
      return false;
    }
    if($('#email').val() == 0){
      alert_message('Please Enter Email', 'info', 'OK');
      return false;
    }
     $('#add_bill_form').submit();
  }

</script>

app/views/bills/add_view_edit_bill.html.erb
<div class="card">
  <div class="card-body table-view">
    <% if params[:type].to_i == 1 %>
      <div><label style="font-size: 40px;">Add Bill</lable></div>
      <br><br>
    <% elsif params[:type].to_i == 2 %>
      <div><label style="font-size: 40px;">Edit Bill</lable></div>
      <br><br>
    <% elsif params[:type].to_i == 3 %>
      <div><label style="font-size: 40px;">View Bill</lable></div>
      <br><br>
    <%end%>
    <%= render 'form' %>
  </div>
</div>

app/views/bills/index.html.erb
<h1>Submitted Bills</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Amount</th>
      <th>Date</th>
      <th>Employee</th>
      <th>Department</th>
    </tr>
  </thead>
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.type %></td>
        <td><%= bill.amount %></td>
        <td><%= bill.created_at.to_date %></td>
        <td><%= bill.employee.first_name %> <%= bill.employee.last_name %></td>
        <td><%= bill.employee.department %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', employees_path %>

app/views/bills/manage_bills.html.erb
<div class="card">
  <div class="card-body table-view">
    <div id="add_new_button" class = "text-right"><%= link_to 'Add Bill', add_view_edit_bill_path(type: 1, user_token: params[:user_token]), class: 'btn btn-primary', role: 'button' %>
      <%= link_to 'Manage Employees', manage_employees_path, class: 'btn btn-primary', role: 'button' %>
    </div>
    <div class="table-responsive pt-4">
      <table id="manage_bills_table" class="table"></table>
    </div>
</div>
<script>
  var savedSearchIndex = '';
  supplier_table = $('#manage_bills_table').DataTable({
        dom: 'frti',
        stateSave: true,
        stateDuration: -1,
        responsive: false,
        autoWidth: false,
        rowGroup: false, 
        stateSaveParams: function(settings, data) {
        },
        stateLoadParams: function(settings, data) {
          data.search.search = savedSearchIndex;
        },
        initComplete: function(settings, json) {
          this.api().search(savedSearchIndex).draw();
          $('.dataTables_filter').attr('data-original-title', 'Please type the search term and press "Enter" or click the search icon').tooltip();
        },
        pageLength: 100,
        paging: true,
        searchDealy: 3000,
        processing: true,
        serverSide: true,
        ajax: {
          url: '<%=get_bill_data_path(user_token: params[:user_token])%>',
          data: function (d) {
            sorting_column = null
             $.each(d.order, function(){
                if (this.dir == 'asc') {
                  sorting_column = this
                }
              })
            return $.extend( {}, d, {
              data_sorting: sorting_column,
            });
          },
          error: function() {
            alert_message('<%= t :grid_load_data_error, grid_type: 'Supplier' %>', 'info', 'OK')
          },
          complete: function(data, settings) {
            
          }
        },
        columns: [
          { title: 'Bill Type', data: 'bill_type', width: "30%", className: 'data-table-content-center'},
          { title: 'Bill Amount', data: 'bill_amount', width: "30%", orderable: false, className: 'data-table-content-center'},
          { title: 'Employee Id', data: 'employee_id', width: "10%", orderable: false, className: 'data-table-content-center' },
          { title: 'Employee Name', data: 'employee_name', width: "20%", orderable: false, className: 'data-table-content-center' },
          { title: 'Actions', data: 'action', width: "10%", orderable: false, className: 'data-table-content-center' }
        ],
        deferRender: true,
        orderClasses: false,
        scrollCollapse: true,
        scrollY: 320,
        scrollX: true,
        scrollCollapse: true,
        columnDefs: [
          {targets: [0], searchable: true}
        ],
        language: {
          search: "_INPUT_",
          searchPlaceholder: "Search Company Name",
          emptyTable: "No Record(s) Found",
          infoEmpty: "",
          zeroRecords: "No Record(s) Found",
          loadingRecords: "Loading...",
          loadingRecords: '<i class="fas fa-spinner fa-pulse fa-2x fa-fw"></i>',
          info: "Showing <b>_START_ to _END_</b> (of _TOTAL_)",
          infoFiltered: "",
          processing: '<i class="fas fa-spinner fa-pulse fa-2x fa-fw"></i>'
        },
        order: [[0,"asc"]],
        stripeClasses: ['odd-row', 'even-row'],
      });

  function delete_reason(token,user_token) {
    $.when(load_third_page("/delete_reason_lightbox/"+user_token+"/"+token, "", "Delete", "GET", "550", "HideThirdDialog()")).then(function() {
      $("body").addClass("modal-open");
      load_maxlength('supplier_delist_relist_other_reason', 'bottom');
      $('[data-toggle="tooltip"]').tooltip();
    });
  }

  function submit_valid() {
    if($('#delete_reason').val() == '') {
      alert_message('Please Provide reason for delete', 'info', 'OK');
      return false;
    } else {
      $('#delete_form').submit();
    }
  }
</script>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= form_with(model: [@employee, @bill], local: true) do |form| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>
      <ul>
        <% @bill.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :type %>
    <%= form.select :type, Bill::TYPES %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', employee_path(@employee) %>